### ISSUE TITLE
A separate lib for Axis?

### ISSUE THREAD

**Issue by anagrius** [terezka/lines#2]
Hi again, been looking into your new lines repo. I guess the goal is to have the libs very modular. I was thinking, in my case I want to be able to switch between lines, area and histogram. In the histogram case that would be bars and not lines!

The axis and labels etc would be the same regardless of visualization.

In our case we will usually have a date time x-axis with the same ticks, positioning, labels etc.  regardless of lines, area or bars.

Have you thought about moving the positioning and axis drawing code into a seperate lib?

**Comment by terezka** [comment]
Hi! I have thought about it, although there seems - especially with bars - to be some crucial differences between the two implementations, making the api muddy when they are squashed.
